### PR TITLE
Update App.vue

### PR DESCRIPTION
**Pull request by diomed**
font

### CODE REVIEW

**Comment by diomed** [comment]
why don't u merge PR?

**Comment by BrockReece** [comment]
Sorry what does this fix?
As far as I can tell it just changes the font on the example page?

**Comment by diomed** [comment]
ah, sorry. at the time I posted it, Lato as google font wasn't properly added, and I switched it to native fonts instead. you can close this if you wish.

**Comment by BrockReece** [comment]
Is it fixed now?

**Comment by diomed** [comment]
I see Lato properly in demo now, so I guess it's fine.

**Comment by BrockReece** [comment]
Awesome, sorry that it took me so long to answer.

**Pull request closed without merging**
